//! New-app scaffold command.
//!
//! Creates the minimal directory structure for a new Nyx app so that it can
//! be added to the workspace without any manual file creation.
//!
//! For an app named `Anteros` the following paths are created under
//! `workspace_root`:
//!
//! ```text
//! apps/Anteros/Anteros-profiles/src/lib.rs   (stub)
//! apps/Anteros/Anteros-profiles/Cargo.toml   (stub)
//! migrations/Anteros/.gitkeep
//! ```
#![warn(clippy::pedantic)]

/// Validate `name` and scaffold a new app directory tree under `workspace_root`.
///
/// # Validation rules
///
/// - Must not be empty.
/// - Characters must be ASCII alphanumeric, `-`, or `.` only (no spaces,
///   `@`, `#`, etc.).
///
/// # Errors
///
/// Returns [`anyhow::Error`] when the name is invalid or a filesystem
/// operation fails.
///
/// # Panics
///
/// Panics if the computed `apps/{name}/{name}-profiles/src` path has no parent
/// directory. This is treated as an invariant violation in scaffold generation.
///
/// # Examples
///
/// ```no_run
/// use tempfile::tempdir;
/// let tmp = tempdir().unwrap();
/// nyx_xtask::commands::new_app::run("Anteros", tmp.path()).unwrap();
/// assert!(tmp.path().join("apps/Anteros/Anteros-profiles/src/lib.rs").exists());
/// ```
pub fn run(name: &str, workspace_root: &std::path::Path) -> anyhow::Result<()> {
    validate_name(name)?;

    // -- apps/{name}/{name}-profiles/src/lib.rs --
    let profiles_src = workspace_root
        .join("apps")
        .join(name)
        .join(format!("{name}-profiles"))
        .join("src");
    std::fs::create_dir_all(&profiles_src)?;

    let lib_rs = profiles_src.join("lib.rs");
    std::fs::write(
        &lib_rs,
        format!("// {name}-profiles service\n//\n// Generated by nyx-xtask new-app.\n"),
    )?;
    tracing::info!(path = %lib_rs.display(), "Created lib.rs stub");

    // -- apps/{name}/{name}-profiles/Cargo.toml --
    let cargo_toml = profiles_src
        .parent()
        .expect("src always has a parent")
        .join("Cargo.toml");
    let package_name = format!("{}-profiles", name.to_lowercase());
    std::fs::write(
        &cargo_toml,
        format!(
            "[package]\n\
             name = \"{package_name}\"\n\
             version.workspace = true\n\
             edition.workspace = true\n\
             license.workspace = true\n\
             repository.workspace = true\n\
             rust-version.workspace = true\n\
             \n\
             [lib]\n\
             name = \"{}\"\n\
             path = \"src/lib.rs\"\n\
             \n\
             [dependencies]\n",
            package_name.replace('-', "_")
        ),
    )?;
    tracing::info!(path = %cargo_toml.display(), "Created Cargo.toml stub");

    // -- migrations/{name}/.gitkeep --
    let migrations_dir = workspace_root.join("migrations").join(name);
    std::fs::create_dir_all(&migrations_dir)?;
    std::fs::write(migrations_dir.join(".gitkeep"), "")?;
    tracing::info!(dir = %migrations_dir.display(), "Created migrations directory");

    tracing::info!(app = %name, "App scaffold complete");
    Ok(())
}

/// Ensure `name` is non-empty and contains only allowed characters.
fn validate_name(name: &str) -> anyhow::Result<()> {
    anyhow::ensure!(!name.is_empty(), "App name must not be empty");
    anyhow::ensure!(
        name.chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '.'),
        "App name '{name}' contains invalid characters — only ASCII alphanumeric, '-', and '.' are allowed"
    );
    Ok(())
}
