-- =============================================================================
-- 0006_reels.up.sql
-- Short-form video (reels) and audio tracks.
--
-- Design notes:
--   AUDIO TRACKS:
--     Audio is a first-class entity. A reel can use:
--       a) Original audio from the creator (original_reel_id IS NULL → platform audio)
--       b) Audio extracted from another creator's reel (original_reel_id IS SET)
--     use_count is denormalized and incremented by Uzume-reels on each reel creation.
--     This powers "trending audio" in Uzume-discover.
--
--   SCORING:
--     score is a float updated by uzume-reels score_updater worker using:
--       score = (view_count * 1.0 + like_count * 3.0 + share_count * 5.0)
--               / (age_hours + 2) ^ gravity
--     gravity ≈ 1.8 (tunable via config, not hardcoded in schema).
--     Higher score → shown more often in algorithmic feed.
--
--   HLS VIDEO:
--     media_key points to the HLS master manifest (.m3u8) in MinIO.
--     Oya transcodes the raw upload into multi-bitrate HLS (1080p/720p/480p).
--     thumbnail_key points to the video poster frame (generated by Oya).
--
--   VIEWS:
--     reel_views are append-only. Watch percent distinguishes loop-throughs
--     from genuine engagement. Scoring weights full watches (≥85%) higher.
--     To prevent write amplification, views are buffered in DragonflyDB and
--     flushed to PostgreSQL in batches by Uzume-reels (every 30s).
-- =============================================================================

-- ── Audio tracks ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Uzume".reel_audio (
    id                  UUID        NOT NULL DEFAULT gen_random_uuid(),
    title               TEXT        NOT NULL,
    artist_name         TEXT,       -- display name shown in the audio attribution UI
    -- NULL = platform-uploaded audio; SET = extracted from another creator's reel
    original_reel_id    UUID,
    -- Path to the processed audio file in MinIO (AAC 128kbps)
    audio_key           TEXT        NOT NULL,
    duration_ms         INTEGER     NOT NULL,
    use_count           BIGINT      NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT reel_audio_pk
        PRIMARY KEY (id),

    -- Self-reference OK (original_reel_id references reels table below, set
    -- via deferred FK after reels table is created — see below).
    CONSTRAINT reel_audio_duration_ck
        CHECK (duration_ms > 0),

    CONSTRAINT reel_audio_title_len
        CHECK (char_length(title) <= 200)
);

-- Trending audio: highest use_count in the last 7 days
CREATE INDEX IF NOT EXISTS reel_audio_use_count_idx
    ON "Uzume".reel_audio (use_count DESC, created_at DESC);

-- ── Reels ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Uzume".reels (
    id                  UUID        NOT NULL DEFAULT gen_random_uuid(),
    author_profile_id   UUID        NOT NULL,
    caption             TEXT        NOT NULL DEFAULT '',
    hashtags            TEXT[]      NOT NULL DEFAULT '{}',

    -- Raw upload key (set immediately)
    raw_key             TEXT        NOT NULL,
    -- HLS master manifest (set by Oya after transcoding)
    media_key           TEXT,
    thumbnail_key       TEXT,

    duration_ms         INTEGER     NOT NULL,
    processing_state    TEXT        NOT NULL DEFAULT 'pending',

    -- Audio attribution
    audio_id            UUID,
    -- Millisecond offset into the audio track where this reel starts playing
    audio_start_ms      INTEGER     NOT NULL DEFAULT 0,

    -- Engagement counters (denormalized; eventually consistent via NATS)
    view_count          BIGINT      NOT NULL DEFAULT 0,
    like_count          BIGINT      NOT NULL DEFAULT 0,
    comment_count       BIGINT      NOT NULL DEFAULT 0,
    share_count         BIGINT      NOT NULL DEFAULT 0,

    -- Algorithmic ranking score (updated by score_updater worker)
    score               DOUBLE PRECISION NOT NULL DEFAULT 0.0,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uzume_reels_pk
        PRIMARY KEY (id),

    CONSTRAINT uzume_reels_author_fk
        FOREIGN KEY (author_profile_id)
        REFERENCES "Uzume".profiles (id)
        ON DELETE CASCADE,

    CONSTRAINT uzume_reels_audio_fk
        FOREIGN KEY (audio_id)
        REFERENCES "Uzume".reel_audio (id)
        ON DELETE SET NULL,

    CONSTRAINT uzume_reels_state_ck
        CHECK (processing_state IN ('pending', 'processing', 'ready', 'failed')),

    CONSTRAINT uzume_reels_duration_ck
        CHECK (duration_ms > 0 AND duration_ms <= 90000),  -- max 90 seconds

    CONSTRAINT uzume_reels_caption_len
        CHECK (char_length(caption) <= 2200),

    CONSTRAINT uzume_reels_audio_start_ck
        CHECK (audio_start_ms >= 0)
);

-- Algorithmic feed: highest-scored ready reels
CREATE INDEX IF NOT EXISTS uzume_reels_score_idx
    ON "Uzume".reels (score DESC, created_at DESC)
    WHERE processing_state = 'ready';

-- Author profile page: newest reels first
CREATE INDEX IF NOT EXISTS uzume_reels_author_idx
    ON "Uzume".reels (author_profile_id, created_at DESC);

CREATE INDEX IF NOT EXISTS uzume_reels_hashtags_idx
    ON "Uzume".reels USING GIN (hashtags);

-- Oya processing queue
CREATE INDEX IF NOT EXISTS uzume_reels_pending_idx
    ON "Uzume".reels (created_at)
    WHERE processing_state = 'pending';

-- ── Back-reference from reel_audio to reels ───────────────────────────────────
-- Set after reels table exists.
ALTER TABLE "Uzume".reel_audio
    ADD CONSTRAINT reel_audio_original_reel_fk
        FOREIGN KEY (original_reel_id)
        REFERENCES "Uzume".reels (id)
        ON DELETE SET NULL;

-- ── Reel likes ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Uzume".reel_likes (
    reel_id             UUID        NOT NULL,
    profile_id          UUID        NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uzume_reel_likes_pk
        PRIMARY KEY (reel_id, profile_id),

    CONSTRAINT uzume_reel_likes_reel_fk
        FOREIGN KEY (reel_id)
        REFERENCES "Uzume".reels (id)
        ON DELETE CASCADE,

    CONSTRAINT uzume_reel_likes_profile_fk
        FOREIGN KEY (profile_id)
        REFERENCES "Uzume".profiles (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS uzume_reel_likes_profile_idx
    ON "Uzume".reel_likes (profile_id, created_at DESC);

-- ── Reel views ────────────────────────────────────────────────────────────────
-- Append-only. High-write table — batched flush from DragonflyDB.
CREATE TABLE IF NOT EXISTS "Uzume".reel_views (
    id                  UUID        NOT NULL DEFAULT gen_random_uuid(),
    reel_id             UUID        NOT NULL,
    viewer_profile_id   UUID        NOT NULL,
    -- 0–100: percentage of the reel the viewer watched.
    -- < 25 = scroll-past, 25–84 = partial, ≥ 85 = full watch (counts as 1 view).
    watch_percent       SMALLINT    NOT NULL DEFAULT 0,
    viewed_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uzume_reel_views_pk
        PRIMARY KEY (id),

    CONSTRAINT uzume_reel_views_reel_fk
        FOREIGN KEY (reel_id)
        REFERENCES "Uzume".reels (id)
        ON DELETE CASCADE,

    CONSTRAINT uzume_reel_views_viewer_fk
        FOREIGN KEY (viewer_profile_id)
        REFERENCES "Uzume".profiles (id)
        ON DELETE CASCADE,

    CONSTRAINT uzume_reel_views_watch_pct_ck
        CHECK (watch_percent BETWEEN 0 AND 100)
);

-- Score updater: "all views for reel R in the last 24h"
CREATE INDEX IF NOT EXISTS uzume_reel_views_reel_recent_idx
    ON "Uzume".reel_views (reel_id, viewed_at DESC);
